# Generated by Django 5.1.3 on 2024-11-11 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_producthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producthistory',
            name='product_code',
        ),
        migrations.AddField(
            model_name='producthistory',
            name='code',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product'),
        ),
        migrations.AddField(
            model_name='producthistory',
            name='title',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
