# Generated by Django 5.1.3 on 2024-11-17 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out',
            field=models.BooleanField(default=False),
        ),
    ]
