# Generated by Django 5.1.3 on 2025-02-24 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_tag_producttag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='productcategory',
            name='product',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
