# Generated by Django 5.1.3 on 2025-03-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_remove_productcategory_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='penalty',
            field=models.FloatField(default=0),
        ),
    ]
