# Generated by Django 5.1.3 on 2025-05-19 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_order_cartitem_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
