# Generated by Django 5.1.3 on 2025-06-01 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_orderitem_order_remove_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='out',
        ),
    ]
